#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "custom_backup"
name = "Custom Backup"
description.en = "Backup extra paths not already managed by YunoHost backup feature"
description.fr = "Sauvegarde des chemins supplémentaires qui ne sont pas déjà géré par le fonctionnalité de sauvegarde de YunoHost"

version = "1.0~ynh1"

maintainers = ["ljf"]

[upstream]
license = "AGPL-3.0-only"
code = "https://github.com/YunoHost-Apps/custom_backup_ynh"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"

disk = "10M"
ram.build = "50M"
ram.runtime = "0M"

[install]
    [install.extra_paths]
    ask.en = "List of extra paths to backup"
    type = "text"
    help.en = "One absolute path per line. You should check each path is not already backup by YunoHost."
    example = "/usr/local/bin/"
    
    [install.services_to_reload]
    ask.en = "Services to reload"
    type = "tags"
    optional = true
    help.en = "Services to reload or restart after a restore."

[resources]
