#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
