#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================


source /usr/share/yunohost/helpers


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
