#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
