#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================



source /usr/share/yunohost/helpers

while IFS= read -r extra_path ; do
    ynh_script_progression --message="Restoring $extra_path..." --weight=1
    ynh_restore_file --origin_path="$extra_path"
done <<< "$extra_paths"
# FIXME: Find a way to reapply owners properly ?

IFS=, read -a services_to_reload_array <<< "$services_to_reload"
for service_to_reload in "${serives_to_reload_array[@]}"; do
    ynh_script_progression --message="Reloading $service_to_reload..." --weight=1
    ynh_systemd_action --service_name=service_to_reload --action=reload
done

# FIXME: Restore a DB ?
# FIXME: Apply custom script ?

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
