#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

while IFS= read -r extra_path ; do
    ynh_script_progression "Restoring $extra_path..."
    ynh_restore "$extra_path"
done <<< "$extra_paths"
# FIXME: Find a way to reapply owners properly ?

IFS=, read -a services_to_reload_array <<< "$services_to_reload"
for service_to_reload in "${serives_to_reload_array[@]}"; do
    ynh_script_progression "Reloading $service_to_reload..."
    ynh_systemctl --service=service_to_reload --action=reload
done

# FIXME: Restore a DB ?
# FIXME: Apply custom script ?

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
